### ISSUE TITLE
Loading available updates not open anymore error 

### ISSUE THREAD

**Issue by mani2care** [xirianlight/openToMoreInfo#2]
@xirianlight  Hi I am using this new version of Loading available updates app and most of the time its working fine but some time i am getting this error or not running it.

I am defining via nudge for the application path its working but some time this error is giving me.

<img width="261" alt="Screenshot 2022-10-27 at 4 59 03 PM" src="https://user-images.githubusercontent.com/52978899/198273724-87688da3-65d9-4d0b-b5f3-bbb1e81a3328.png">

**Comment by mani2care** [comment]
App is not hiding from Launchpad is the issue presently now above issue is resolved thanks xirian

**Comment by xirianlight** [comment]
User reported symptom resolved in Slack.
