### ISSUE TITLE
Tried Running Apple Script in Ventura 13.0

### ISSUE THREAD

**Issue by Ninjastic-Ninja** [xirianlight/openToMoreInfo#3]
Tried running it in Mac OS Ventura 13.0 and it went to system preferences pane and didn't click on update now button , same works in Mac OS 12 . 

Ran code apple script v2 in apple script editor but didn't went though to click on update button

**Comment by xirianlight** [comment]
I've updated the v2 text to better reflect the last production test I was using - give it a spin when convenient.

**Comment by Ninjastic-Ninja** [comment]
Updated script is working as expected in Ventura, Thank you so much
