### ISSUE TITLE
Seeing prompt in macOS Monterey 

### ISSUE THREAD

**Issue by Ninjastic-Ninja** [xirianlight/openToMoreInfo#4]
While using More info loader in macOS Monterey , It gives an automation prompt to approve manually which doesn't seems approve automatically . Attaching snapshot 

Is there a way to bypass this ?

<img width="153" alt="Screenshot 2022-12-21 at 12 18 14 AM" src="https://user-images.githubusercontent.com/39200937/212889705-9432f9e6-888f-4984-bc7c-e7b8e5967883.png">

**Comment by xirianlight** [comment]
This means your PPPC profile for the app isn't configured correctly or has not been deployed. See section 2 of the readme for more information, here's the [sample profile](https://github.com/xirianlight/openToMoreInfo/blob/main/PPPC%20-%20Loading%20Available%20Updates.mobileconfig), and if the sample profile doesn't work for you, I'd recommend creating a custom one using [PPPC Utility](https://github.com/jamf/PPPC-Utility).

**Comment by Ninjastic-Ninja** [comment]
This seems to be issue with config profile path , Works well with Monterey as well . Thanks !!
